server:
  grpc:
    addr: 0.0.0.0:9001
    timeout: 10s
  http:
    addr: 0.0.0.0:9101
    timeout: 5s

data:
  database:
    driver: mysql
    source: mysql://like:like123456@localhost:13306/xlike_user?parseTime=True&loc=Asia%2FShanghai
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

nacos:
  address: 127.0.0.1
  port: 8848